<?php
/**
 * Created by PhpStorm.
 * User: Vassya
 * Date: 07.02.2015
 * Time: 12:26
 */

//print_r($users);
?>
<table class="table">
    <tr>
        <th>Login</th>
        <th>First Name</th>
        <th>Second Name</th>
        <th>Admin/User</th>
    </tr>
    <?php foreach($users as $user) : ?>
        <tr>
            <td><?php echo $user->login;?></td>
            <td><?php echo $user->first_name;?></td>
            <td><?php echo $user->second_name;?></td>
            <td><?php echo $user->type;?></td>
        </tr>
    <?php endforeach; ?>
</table>